### ISSUE TITLE
Citizen not getting mail from supervisor.

### ISSUE THREAD

**Issue by jcgertig** [Akamaozu/node-supe#12]
When I try to send mail to a citizen from the supervisor like so `supe.mail.send({ to: 'citizen' }, content)` I get recipient does not exist error. How am i supposed to do this?

**Comment by jcgertig** [comment]
Im doing this for now
```
supervisor.noticeboard.notify('received-mail-from-citizen', { from: 'parent', to: 'citizen', type: 'mail', msg: 'content' });
```
It works

**Comment by Akamaozu** [comment]
Mail module's not very intuitive from the supervisor side. Sorry about that.

Here's what you want:

```js
// inside supervisor
var supervisor = require('supe')(),
    citizen = supervisor.register( 'citizen', './citizen.js');

citizen.mail.send( 'content' );
// or
supervisor.get('citizen').mail.send( 'content' );
```

You need the citizen instance, then use the instance's `mail.send`.

**Comment by Akamaozu** [comment]
@jcgertig here's an example from the tests

https://github.com/Akamaozu/node-supe/blob/master/test/test.js#L690-L714

**Comment by Akamaozu** [comment]
@jcgertig were you able to send mail to the citizen using the methods I described?

**Comment by jcgertig** [comment]
I have not but from my understanding that is not what I want I want the citizen to get the mail not the supervisor unless you are saying `supervisor.get('citizen').mail.send({ to: 'citizen' }, 'content' );`

**Comment by jcgertig** [comment]
And then my `from` would be `'citizen'` but I would like it to be something like `'parent'`

**Comment by jcgertig** [comment]
I turn my example into 
```
function addMail (_supervisor) {
  return new Proxy(_supervisor, {
    get: function(supervisor, prop) {
      if (prop in supervisor) {
        return supervisor[prop];
      }
      if (prop === 'mail') {
        return {
          send: (settings, msg) => {
            if (!msg) {
              msg = settings;
              settings = {};
            }
            let envelope = Object.assign({ from: 'parent', type: 'mail' }, settings, { msg });
            supervisor.noticeboard.notify('received-mail-from-citizen', envelope);
          },
          receive: (handler = () => {}) => {
            supervisor.noticeboard.watch('supervisor-message', 'handle-supervisor-message', ({ notice }) => {
              handler(notice, () => {});
            });
          }
        };
      }
      return undefined;
    }
  });
}
```
So I can do:
```
supervisor = addMail(supervisor);
supervisor.mail.receive(({ from, msg }) => {
 // handle mail
});
supervisor.mail.send({ to: 'citizen' }, 'content');
```

**Comment by Akamaozu** [comment]
You really should try the sample code. 

It does exactly what you're asking: sends mail from the supervisor to the citizen.

**Comment by Akamaozu** [comment]
@jcgertig

Let me explain what my initial example code does.

`supervisor.get` returns a citizen instance. Each citizen instance has `mail.send`, which handles adding the mail and signaling the citizen process that it has mail (if it didn't have any before)

**Comment by jcgertig** [comment]
Okay I switched my proxy to:

```
send: (settings, msg) => {
  if (!settings.to) { return; }
  supervisor.get(settings.to).mail.send(msg);
}
```
I'm still using this because the api `supervisor.mail.send({ to: '' }, 'content')` makes more sense when read.

**Comment by Akamaozu** [comment]
That api definitely makes more sense because it matches what you'd use in the citizen.
